# Generated by Django 4.0.4 on 2022-07-23 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_remove_profile_add_info_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
