# Generated by Django 4.0.4 on 2022-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0006_developermode'),
    ]

    operations = [
        migrations.AddField(
            model_name='developermode',
            name='name',
            field=models.CharField(default='name', max_length=225),
        ),
    ]
